version: "3.9"

services:
  rabbitmq:
    build: rabbitmq/.
    networks:
    - "rabbitnet"

    # for consumers
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  client_app:
    build: .
    networks:
    - "rabbitnet"
    env_file:
      - .env
    environment:
      - RABBITMQ-HOST=rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
        - rabbitmq

networks:
  rabbitnet: