version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3"
    networks:
    - "rabbitnet"
    ports:
      - "5672:5672"

  client_app:
    build: .
    networks:
    - "rabbitnet"
    env_file:
      - .env

networks:
  rabbitnet: